# .github/workflows/deploy.yml

name: Deploy Wiki to GitHub Pages

on:
  # Run on pushes to the main branch
  push:
    branches:
      - main
  # Allow manual runs from the Actions tab
  workflow_dispatch:

# IMPORTANT: This grants the workflow permission to push to your gh-pages branch.
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the main branch
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3. Install dependencies from our requirements file
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Build the site and deploy it to the gh-pages branch
      - name: Deploy
        run: mkdocs gh-deploy --force
